<?php

namespace Database\Seeders;

use App\Models\Classe;
use Illuminate\Database\Seeder;

class ClassesTableSeeder extends Seeder
{
    public function run(): void
    {
        $classes = [
            [
                'nome'                   => 'Bárbaro',
                'versao'                 => '3.5',
                'descricao'              => 'Guerreiro feroz das terras selvagens que canaliza a fúria de batalha como arma. Bárbaros são pessoas rústicas e temperamentais que preferem os desafios brutais da natureza aos refinamentos da civilização — vivem em tribos nômades, aldeias fronteiriças ou solidão nas montanhas. Habilidade central: Fúria — usada 1 vez por dia no 1° nível (mais usos com o avanço, até 6/dia no 20°), concede +4 de Força e Constituição, +2 de moral em TRs de Vontade e -2 na Classe de Armadura por 3+CON rodadas; após a fúria, o bárbaro fica fatigado. Complementam a classe: Deslocamento Rápido (+3 m de deslocamento base), Sentido de Perigo (+1 nos Reflexos e CA contra armadilhas por nível de 3 em 3), Esquiva Sobrenatural (2° nível — não perde bônus de DES quando surpreso ou flanqueado), Esquiva Sobrenatural Aprimorada (5° — imune a flanqueio exceto por ladino 4+ níveis acima), Redução de Dano crescente a partir do 7° (RD 1/— aumentando até RD 5/— no 19°), Fúria Maior (11° — +6 nos atributos), Fúria Incansável (17° — sem fadiga pós-fúria) e Fúria Poderosa (20° — +8 nos atributos). Atributo primário: Força (dano em melee) e Constituição (PVs e duração da fúria). Dado de Vida d12 é o maior do jogo. BBA Boa, Fortitude Boa, Reflexos e Vontade Ruins. Alinhamento não pode ser leal (a disciplina rígida da lei incompatibiliza-se com a fúria selvagem). Proficiências: todas as armas simples e marciais, armaduras leves, médias e pesadas, escudos (exceto torre). Analfabeto por padrão — precisa gastar 2 pontos de perícia para aprender a ler. Estilo de jogo: tanque agressivo com PVs enormes e potencial de dano explosivo em combate por rodadas limitadas — melhor em campanhas de aventura direta com muitos combates curtos. Multiclasse restrita: um bárbaro que se torne leal (via magia ou escolha) perde permanentemente a habilidade de Fúria.',
                'dado_vida'              => 12,
                'bba_progressao'         => 'boa',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'ruim',
                'pontos_pericia'         => 4,
            ],
            [
                'nome'                   => 'Bardo',
                'versao'                 => '3.5',
                'descricao'              => 'Artista errante cuja música mágica e vasto conhecimento tornam-no o mais versátil aventureiro. Bardos são performers itinerantes — trovadores, contadores de histórias, atores, poetas — que absorvem conhecimento de todo lugar por onde passam e transformam sua arte em poder tangível. Habilidade central: Música de Bardo — usada por rodadas iguais ao nível/dia, oferece diferentes efeitos conforme o nível: Contrafeitiço (mesma ideia que Contra-magia mas via performance), Encorajamento (bônus de moral +1 em ataques e dano para aliados que ouvem, +2 no 8° nível, +3 no 14°, +4 no 20°), Fascinar (1° — hipnotiza inimigos por 1 rodada/nível), Sugestão (6° — sugestão via música), Inspirar Coragem, Inspirar Competência, Inspirar Grandeza (9°), Suggestão em Massa (12°), Inspirar Heroísmo (15°) e Grito de Morte (20°). Bardos também têm Conhecimento de Bardo (soma nível + INT em qualquer verificação de conhecimento não treinado — bibliotecário universal do grupo), listas extensas de perícias (bardo tem mais perícias de classe que qualquer classe), e conjuração arcana espontânea da lista de bardo (6° círculo máximo). Diferente do feiticeiro, o bardo tem magias conhecidas fixas por nível mas as lança sem preparo. Atributo primário: Carisma (magias e música). Dado de Vida d6, BBA Média, Fortitude Ruim, Reflexos e Vontade Boas, 6 pontos de perícia por nível. Alinhamento não pode ser leal (a mesma restrição do bárbaro — a espontaneidade artística resiste à rigidez legal). Proficiências: armas simples + arco longo, arco curto, chicote, rapieira, espada curta, espada bastarda; armaduras leves (não impõe falha arcana em suas magias — vantagem única do bardo); escudos leves; sem armaduras médias/pesadas ao conjurar. Estilo de jogo: hábil coringa — nunca o melhor em qualquer papel, mas presente em todos ao mesmo tempo. Excelente em campanhas com narrativa social forte, exploração e combates onde suporte é valorizado.',
                'dado_vida'              => 6,
                'bba_progressao'         => 'media',
                'resistencia_fortitude'  => 'ruim',
                'resistencia_reflexos'   => 'boa',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 6,
            ],
            [
                'nome'                   => 'Clérigo',
                'versao'                 => '3.5',
                'descricao'              => 'Sacerdote guerreiro que canaliza os poderes divinos de sua deidade para o mundo mortal. Clérigos são combatentes espirituais — servos escolhidos de deuses específicos, cujas magias são orações concedidas e cuja força divina os torna simultaneamente curadores e destruidores. Habilidade central: Conjuração Divina — preparam magias divinas diariamente da lista completa de clérigo (até 9° círculo). Diferente do mago, o clérigo tem acesso a TODAS as magias da sua lista sem precisar registrá-las em grimório — a lista inteira do PHB está disponível para escolha diária. Domínios: cada clérigo escolhe dois domínios divinos apropriados à sua divindade, cada um concedendo uma magia bônus por círculo de conjuração (armazenada em espaço próprio) e uma habilidade especial (por exemplo, Domínio da Guerra dá proficiência com a arma favorita do deus + Foco em Arma; Domínio da Cura dá conjuração espontânea aprimorada de curas; Domínio do Sol dá poder de expulsão adicional). Conjuração Espontânea: um clérigo bondoso pode converter qualquer magia preparada em uma magia de Curar Ferimentos do mesmo círculo instantaneamente (crítica em emergências); um clérigo maligno converte em magias de Infligir; neutros escolhem uma vez qual conversão usar. Expulsão de Mortos-Vivos: 3+CAR vezes por dia, canaliza energia positiva (bons e neutros) ou negativa (malignos) para afugentar (ou controlar, para malignos) mortos-vivos até 2×nível do clérigo em HD. Aura: aura sobrenatural que corresponde ao alinhamento do deus (detectável por Detectar o Mal/Bem/Lei/Caos). Alinhamento: dentro de um passo do alinhamento do deus. Atributo primário: Sabedoria (magias); Força/Constituição secundários (combate). Dado de Vida d8, BBA Média, Fortitude e Vontade Boas, Reflexos Ruim, 2 pontos de perícia por nível. Proficiências: todas as armas simples + arma favorita do deus, todas as armaduras e escudos (exceto torre). Estilo de jogo: fundação essencial de qualquer grupo — cura, buffs, controle de mortos-vivos e capaz de suportar melee ligeiro. Classe versátil que se adapta a qualquer campanha.',
                'dado_vida'              => 8,
                'bba_progressao'         => 'media',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 2,
            ],
            [
                'nome'                   => 'Druida',
                'versao'                 => '3.5',
                'descricao'              => 'Guardião da natureza selvagem que canaliza os poderes elementais dos ciclos naturais. Druidas são os sacerdotes das florestas, montanhas, tundras e desertos — servos não de deuses antropomórficos, mas da própria Natureza como conceito cósmico. Rejeitam a civilização como uma corrupção antinatural. Habilidade central: Forma Selvagem — no 5° nível, druida pode transformar-se em qualquer animal Pequeno ou Médio 1 vez por dia, ganhando todas as habilidades físicas da criatura (Força, Destreza, deslocamento, ataques naturais, sentidos especiais). Nos níveis superiores: no 6° pode virar animal Grande (2x/dia); no 8° acesso ao formato elemental (Elemento Pequeno); no 10° acesso a Elementos Médios; nos 12° em diante, aumenta o poder das transformações. Cada aplicação dura horas equivalentes ao nível de druida. Companheiro Animal: druida ganha um companheiro animal desde o 1° nível — geralmente um lobo, urso, tigre ou pantera dependendo da região. O companheiro cresce em poder conforme o druida sobe de nível, ganhando bônus de PVs, atributos, redução de dano, evasão e outras vantagens. Conjuração Divina: druida prepara magias divinas de sua lista específica (até 9° círculo). Magias da natureza (Entrelaçar, Chamado da Natureza, Controle Meteorológico, Terremoto) dominam a lista. Habilidades adicionais: Sentido da Natureza, Empatia Selvagem (adestrar criatura naturalmente), Passo Silencioso (não deixa rastros), Percurso pela Selva (movimento normal em terreno difícil natural), Resistir ao Chamado da Natureza (bônus contra Encantar em fadas), Imunidade a Venenos (9°), Mil Faces (13° — polimorfe autopermanente), Corpo Atemporal (15° — não envelhece). Alinhamento: qualquer neutro (Verdadeiro Neutro, Leal Neutro, Neutro Bondoso, Neutro Maligno ou Caótico Neutro). Atributo primário: Sabedoria. Dado de Vida d8, BBA Média, Fortitude e Vontade Boas, Reflexos Ruim, 4 pontos de perícia por nível. Proficiências: armas simples selecionadas (clava, adaga, dardo, azagaia, lança, funda, cimitarra, cajado); armaduras leves ou médias sem metal (couro, couro tachonado); escudos de madeira. Um druida que use armadura ou escudo de metal perde acesso a magias e Forma Selvagem por 24 horas. Estilo de jogo: guardião polivalente — combatente feroz em Forma Selvagem, curador divino de natureza, invocador de aliados naturais e mestre da mudança de terreno em combate.',
                'dado_vida'              => 8,
                'bba_progressao'         => 'media',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 4,
            ],
            [
                'nome'                   => 'Feiticeiro',
                'versao'                 => '3.5',
                'descricao'              => 'Conjurador arcano nascido com magia no sangue — ancestralidade dracônica, herança celestial, corrupção infernal ou simplesmente uma gota de puro poder cósmico correndo em suas veias. Feiticeiros são contrários ao mago em quase tudo: enquanto o mago estuda, o feiticeiro sente; enquanto o mago tem repertório enorme, o feiticeiro tem magias intensivas. Habilidade central: Conjuração Espontânea — feiticeiros preparam magias arcanas espontaneamente (não precisam preparar antecipadamente) da sua lista de conhecidas. Você aprende novas magias em níveis fixos: começa com 4 truques + 2 magias de 1° círculo conhecidos no 1° nível, aprendendo total de 9 truques e mais magias por círculo conforme sobe. Não pode aprender magias fora dos slots normais — não estuda grimórios, não copia magias, apenas ganha novas conforme "revelações internas". Em compensação, tem mais espaços de magia por dia do que o mago no mesmo círculo — pode conjurar cada magia conhecida mais vezes. Familiar: no 1° nível, o feiticeiro pode invocar um familiar (gato, coruja, morcego, cobra, sapo, coelho, doninha, gralho, rato — do PHB), que fornece benefícios variáveis: familiar dá +2 de bônus em uma perícia específica, é psíquico com o mestre (percepção compartilhada, comunicação telepática dentro de 1,5 km), e permite armazenar magias tocando. O familiar cresce com o mestre, ganhando poderes especiais. Progressão de conjuração: alcança magias de 9° círculo no 17° nível — 3 níveis à frente do mago no acesso ao 9°, mas depois iguala. Atributo primário: Carisma (define quantas magias por dia, CD dos TR e a máxima potência). Dado de Vida d4 (frágil como o mago), BBA Ruim, Fortitude e Reflexos Ruins, Vontade Boa, 2 pontos de perícia por nível. Proficiências: armas simples apenas; sem armaduras (armaduras causam falha arcana nas magias — proibitivo para feiticeiro que depende totalmente de magia); sem escudos ao conjurar. Estilo de jogo: especialista em algumas magias favoritas que domina completamente. Menor flexibilidade dia-a-dia que o mago, mas maior potência sustentada em cada dia. Ideal para jogadores que preferem menos decisões de preparação e mais uso frequente de magias predileta.',
                'dado_vida'              => 4,
                'bba_progressao'         => 'ruim',
                'resistencia_fortitude'  => 'ruim',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 2,
            ],
            [
                'nome'                   => 'Guerreiro',
                'versao'                 => '3.5',
                'descricao'              => 'Mestre absoluto do combate marcial, treinado exaustivamente em todas as armas e armaduras. Guerreiros são a coluna vertebral de qualquer exército medieval e o membro mais confiável em melee de qualquer grupo aventureiro — cada nível é uma nova camada de perícia bélica. Habilidade central: Talentos de Bônus — guerreiros ganham um talento bônus no 1° nível e, depois, um talento bônus adicional a cada 2 níveis (1°, 2°, 4°, 6°, 8°, 10°, 12°, 14°, 16°, 18°, 20°), totalizando 11 talentos bônus ao longo da carreira — mais do que qualquer outra classe. Esses talentos devem ser escolhidos de uma lista específica: talentos de guerreiro incluem todos os relacionados a combate direto (Ataque Poderoso, Ataque Concentrado, Golpe Ofensivo, Deriva de Ataque, Ataque Especial em melee, Precisão em Ataque, Foco em Arma, Especialização em Arma, Foco Maior em Arma, Especialização Maior em Arma, Tiro em Movimento, Precisão em Tiro, etc.), permitindo especialização profunda em qualquer estilo. Diferentemente de outras classes, o guerreiro não precisa gastar seus talentos gerais nesses talentos de combate — usa os talentos bônus. Atributos primários: Força (dano em melee) OU Destreza (arqueiro/scout), Constituição (PVs). Dado de Vida d10, BBA Boa (máximo do jogo), Fortitude Boa, Reflexos e Vontade Ruins, 2 pontos de perícia por nível (a menor no PHB — reflexo da dedicação total ao treinamento marcial). Proficiências: TODAS as armas simples e marciais, todas as armaduras leves, médias e pesadas, todos os escudos (incluindo escudos torre). É a única classe com essa proficiência universal. Não tem restrição de alinhamento — qualquer alinhamento pode ser guerreiro. Estilo de jogo: chassi universal para construir qualquer conceito de combatente físico. Um guerreiro tanque, um arqueiro, um cavaleiro montado, um mestre de duas armas, um lanceiro — todos podem ser guerreiros de linhagem, diferenciados apenas por escolhas de talento e equipamento. Simples de jogar, poderoso em qualquer estilo, e a classe mais confiável para novos jogadores que querem combatente puro sem magias.',
                'dado_vida'              => 10,
                'bba_progressao'         => 'boa',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'ruim',
                'pontos_pericia'         => 2,
            ],
            [
                'nome'                   => 'Ladino',
                'versao'                 => '3.5',
                'descricao'              => 'Especialista em furtividade, armadilhas e golpes traiçoeiros — o oportunista consumado de qualquer grupo aventureiro. Ladinos são batedores, batedores de bolso, arrombadores, espiões, assassinos ou simplesmente aventureiros que preferem inteligência a força bruta. Habilidade central: Ataque Furtivo — quando o ladino ataca um alvo desprevenido (que não percebeu o ataque, atacado pelas costas), flanqueado (atacado por dois lados) ou negado à Destreza (paralisado, indefeso, sob efeito de certas magias), soma dano extra: +1d6 no 1° nível, +1d6 adicional a cada 2 níveis subsequentes, totalizando até +10d6 no 19° nível. Ataque Furtivo funciona com qualquer arma em melee ou à distância dentro de 9 m; alvo deve ser vulnerável a dano crítico (constructos, mortos-vivos, elementais e criaturas com concealment tornam o Ataque Furtivo mais difícil ou impossível). Descoberta de Armadilhas: apenas ladinos podem detectar armadilhas mágicas com CD 21+ (via Percepção); apenas ladinos podem desativar armadilhas mágicas (via Desativar Dispositivo). Sentido de Armadilha: bônus crescente +1 (3°), +2 (6°), etc. em Reflexos contra armadilhas e CA contra ataques delas. Evasão (2° nível): passar em TR Reflexos para dano de área evita completamente o dano em vez de reduzir à metade. Evasão Aprimorada (10° nível): mesmo se falhar no TR, sofre apenas dano à metade. Esquiva Sobrenatural (4° nível): não perde bônus de DES quando surpreso ou flanqueado. Esquiva Sobrenatural Aprimorada (8° nível): não pode ser flanqueado (exceto por ladino 4 níveis acima). Habilidades Especiais de Ladino (10°, 13°, 16°, 19°): escolha entre Rufião (dano extra por golpe furtivo), Ataque Adaptável (troca dano furtivo por outro efeito), Mente Escorregadia (novo TR contra Encantamento), Oportunista (ataque livre quando aliado acerta o alvo), Golpe Furtivo à Distância Ampliado (aumenta alcance de 9 m para 18 m), etc. Atributos primários: Destreza (esquiva, ataques à distância, várias perícias), Inteligência (mais pontos de perícia), Carisma (perícias sociais). Dado de Vida d6, BBA Média, Fortitude e Vontade Ruins, Reflexos Boa, 8 pontos de perícia por nível (o máximo entre classes básicas). Proficiências: armas simples + boleadeira, besta de mão, punhal duplo, espada curta, chicote, rapieira; armaduras leves; sem escudos. Estilo de jogo: coringa versátil que resolve problemas fora do combate (perícias) e maximiza dano em rodadas específicas por meio de posicionamento e táticas. Costuma preferir combates com muitos aliados (mais flanqueios) e evitar encontros com criaturas imunes a dano crítico.',
                'dado_vida'              => 6,
                'bba_progressao'         => 'media',
                'resistencia_fortitude'  => 'ruim',
                'resistencia_reflexos'   => 'boa',
                'resistencia_vontade'    => 'ruim',
                'pontos_pericia'         => 8,
            ],
            [
                'nome'                   => 'Mago',
                'versao'                 => '3.5',
                'descricao'              => 'Conjurador arcano estudioso que registra magias em um grimório e as prepara diariamente por meio de intenso estudo intelectual. Magos são acadêmicos, sábios e artesãos do arcano — a antítese do feiticeiro emotivo. Habilidade central: Grimório e Preparação — o mago começa a carreira com um grimório contendo os 3 truques de sua lista e 3 magias de 1° círculo escolhidas. A cada nível de conjuração ganho (2°, 3°, etc.), aprende automaticamente 2 novas magias para adicionar ao grimório. Mais importante: qualquer magia arcana da lista de mago encontrada em outros grimórios, pergaminhos ou tomos pode ser aprendida com um teste de Identificar Magia (CD 15 + nível da magia) e um custo em componentes materiais (100 PO por página, aproximadamente). Como resultado, o grimório de um mago experiente pode conter centenas de magias diferentes — mais que qualquer outra classe. Cada dia, o mago escolhe quais magias preparar em cada espaço disponível: se escolher errado (não previr uma situação), fica sem a magia certa; se escolher bem, tem exatamente o que precisa. Especialização de Escola (opcional): no 1° nível, o mago pode escolher uma escola de especialização (Abjuração, Conjuração, Adivinhação, Encantamento, Evocação, Ilusão, Necromancia ou Transmutação), ganhando um espaço de magia adicional por círculo daquela escola. Em troca, deve abandonar duas escolas opostas (chamadas escolas proibidas), das quais nunca pode preparar magias. Uma escola alternativa é ser Mago Universal (não-especializado), que não ganha slot bônus mas tem acesso a todas as escolas. Familiar: mesma habilidade do feiticeiro — invocar familiar (gato, coruja, morcego etc.) no 1° nível, ganhando bônus temáticos e comunicação telepática. Atributo primário: Inteligência (define quantas magias preparadas por dia, CD dos TR e a máxima potência). Dado de Vida d4 (o mais frágil do jogo), BBA Ruim, Fortitude e Reflexos Ruins, Vontade Boa, 2 pontos de perícia por nível. Proficiências: armas simples selecionadas (adaga, bordão, cimitarra leve, dardo, funda, azagaia); sem armaduras nem escudos ao conjurar (falha arcana). Estilo de jogo: máxima versatilidade e adaptação dia-a-dia — o mago é o "arsenal universal" do grupo, mas requer planejamento cuidadoso e leitura das situações. Ideal para jogadores estratégicos que gostam de otimizar recursos e antecipar problemas.',
                'dado_vida'              => 4,
                'bba_progressao'         => 'ruim',
                'resistencia_fortitude'  => 'ruim',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 2,
            ],
            [
                'nome'                   => 'Monge',
                'versao'                 => '3.5',
                'descricao'              => 'Artista marcial disciplinado que transcende os limites físicos cultivando o ki interior por décadas de treinamento monástico. Monges são combatentes-místicos sem paralelo — vivem em monastérios remotos ou peregrinações intermináveis pelas terras conhecidas em busca de perfeição espiritual através do corpo. Habilidade central: Ataques Desarmados Aprimorados — o monge trata seus próprios punhos, cotovelos, joelhos e pés como armas letais. Dano de ataque desarmado por nível: 1d6 (1°-3°), 1d8 (4°-7°), 1d10 (8°-11°), 2d6 (12°-15°), 2d8 (16°-19°), 2d10 (20°). Isso é dano de arma marcial pesada nas mãos vazias. Rajada de Golpes — o monge pode fazer ataques extras em uma rodada quando faz ataque total, com penalidade acumulada -2 em todos os ataques da rodada, permitindo até 5+ ataques por rodada em altos níveis. Bônus na CA (2° nível): monge não pode usar armadura, mas ganha bônus de sabedoria à CA + 1 por 4 níveis (máximo +5). Movimento Rápido (3° nível): +3 m no deslocamento base, subindo até +9 m no 18° nível — monges de alto nível correm mais rápido que cavaleiros. Queda Suave (4°): perto de parede, cai 6 m menos altura calculada. Golpe Ki (5°): ataques desarmados contam como mágicos para contornar redução de dano. Corpo Puro (5°): imunidade a doenças (mesmo mágicas). Domínio do Ki (6°+): usa reserva de ki para efeitos especiais — golpes elementais, movimentos surpresos, magias limitadas via Escola do Ki. Corpo de Diamante (11°): imunidade a venenos. Alma de Diamante (13°): Resistência à Magia igual a 10+nível. Palma Vibrante (15°): 1 vez por semana, marca um alvo desarmado; o monge pode escolher matá-lo instantaneamente até 24 horas depois. Corpo Vazio (19°): pode se tornar etéreo por 1 rodada/nível/dia. Ser Perfeito (20°): torna-se manifestação sobrenatural — vive para sempre, imune a envelhecimento, imortal exceto por violência. Alinhamento: deve ser leal (a disciplina rígida define a classe). Atributos primários: Sabedoria (CA, várias habilidades), Destreza (CA e ataques), Constituição (PVs). Dado de Vida d8, BBA Média, Fortitude, Reflexos e Vontade Boas (única classe com três TRs Boas — a melhor resistência do jogo), 4 pontos de perícia por nível. Proficiências: armas simples (grosso modo — punhal, dardo, azagaia, funda, bordão) + adaga de vento, kama, nunchaku, sai, shuriken, siangham (armas monásticas exóticas); sem armaduras nem escudos (perde a maioria dos bônus da classe se usar). Estilo de jogo: guerreiro móvel de habilidades místicas — muitos ataques por rodada, defesas superiores, mobilidade excepcional. Excelente contra magos (Alma de Diamante), inimigos venenosos (Corpo de Diamante) e grupos numerosos (rajada de golpes). Depende de vários atributos altos para funcionar bem, o que faz do monge o "sofrido em pontos de atributo" da lista.',
                'dado_vida'              => 8,
                'bba_progressao'         => 'media',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'boa',
                'resistencia_vontade'    => 'boa',
                'pontos_pericia'         => 4,
            ],
            [
                'nome'                   => 'Paladino',
                'versao'                 => '3.5',
                'descricao'              => 'Guerreiro sagrado dedicado a uma deidade bondosa, campeão da luz e destruidor do mal. Paladinos são a personificação da virtude marcial — heróis lendários que combinam habilidades marciais superiores com dons divinos concedidos por sua devoção inabalável. Alinhamento: DEVE ser Leal e Bom. Qualquer desvio permanente do alinhamento — ato caótico ou maligno — resulta na perda IMEDIATA de todas as habilidades sobrenaturais (Detectar o Mal, Graça Divina, Imposição das Mãos, Cura Divina, Aura de Coragem, Expulsão, Golpe Sagrado, Corcel Celestial e magias). Paladino que perde poderes deve buscar redenção via magia Expiação para recuperá-los, custosa e ritualística. Habilidades sobrenaturais: Detectar o Mal (à vontade, ação padrão — funciona como a magia, gratuito e ilimitado). Graça Divina (2° nível): bônus de deflexão igual ao modificador de Carisma em todos os testes de resistência. Imposição das Mãos (2°): cura até (nível × CAR-mod) PVs por dia, distribuídos como preferir; contra mortos-vivos, funciona como dano. Aura de Coragem (3°): imunidade a medo para o paladino e aliados em 3 m recebem +4 em TR contra medo. Cura Divina (3°): imunidade a doenças (inclusive mágicas). Golpe Sagrado (1° nível, 1x/dia; adicionais em 5°, 10°, 15°, 20°): faz um ataque em melee contra criatura má com bônus adicional de dano igual ao nível de paladino; se acertar um afugentado ou incapaz de resistir, dobra o dano. Expulsão de Mortos-Vivos (4°): como clérigo 3 níveis abaixo. Remoção de Doenças (6°+, 1x/semana; adicionais em níveis crescentes). Conjuração Divina: paladino ganha magias divinas limitadas a partir do 4° nível — máximo 4° círculo (topo). Corcel Celestial (5°): 1 vez a cada 2 dias, pode convocar um corcel celestial mágico — um cavalo pesado especial com poderes extras que sobem com o paladino (deslocamento aprimorado, RD, resistência a energias, comunicação telepática, evasão). Atributos primários: Carisma (Graça Divina, Golpe Sagrado, TR), Força (dano em melee), Constituição (PVs). Dado de Vida d10, BBA Boa, Fortitude Boa, Reflexos e Vontade Ruins, 2 pontos de perícia por nível. Proficiências: todas as armas simples e marciais, todas as armaduras, todos os escudos (exceto torre). Estilo de jogo: combatente-líder resistente, com utilidade sagrada contra mortos-vivos e forças do mal. Menos poder marcial puro que o guerreiro (menos talentos bônus), mas compensa com magias, cura de campo e Golpe Sagrado devastador. Rígida em role-playing — jogar paladino é aceitar restrições éticas absolutas, o que pode ser desafiador em campanhas moralmente cinzentas.',
                'dado_vida'              => 10,
                'bba_progressao'         => 'boa',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'ruim',
                'resistencia_vontade'    => 'ruim',
                'pontos_pericia'         => 2,
            ],
            [
                'nome'                   => 'Patrulheiro',
                'versao'                 => '3.5',
                'descricao'              => 'Caçador, batedor e rastreador das terras selvagens, especializado em perseguir e destruir tipos específicos de inimigos. Patrulheiros são scouts que conhecem florestas, montanhas e desertos como suas próprias palmas — combinam habilidades marciais de guerreiro com magia divina limitada e conexão profunda com a natureza (como druida). Habilidade central: Inimigo Favorito — no 1° nível, patrulheiro escolhe UM tipo específico de criatura (aberrações, animais, constructos, dragões, fadas, gigantes, humanoides monstruosos, mortos-vivos, ou humanoides de subtipo específico como orcs, goblinoides, elfos-negros etc.), ganhando +2 nas verificações de Blefar, Ouvir, Percepção, Sentir Motivação e Sobrevivência contra ele, além de +2 no dano em ataques contra ele. A cada 5 níveis (5°, 10°, 15°, 20°), o bônus contra o inimigo favorito original aumenta em +2, ou ele pode escolher NOVO inimigo favorito começando em +2. Progressão: no 20° nível, patrulheiro pode ter até 5 inimigos favoritos, com o mais antigo tendo +10 de bônus. Estilo de Combate: no 2° nível, o patrulheiro escolhe entre Combate com Duas Armas (recebe TWF, mesmo sem cumprir pré-requisitos; Aprimorado no 6° nível; Maior no 11°) ou Arqueiro (Rapid Shot no 2°, Manyshot no 6°, Improved Precise Shot no 11°). A escolha determina o estilo de combate por toda a carreira. Companheiro Animal (4° nível): patrulheiro ganha um companheiro animal similar ao do druida (mas de menor poder — como se o patrulheiro fosse 3 níveis menor de druida). Rastreamento: bônus de talento gratuito Rastreamento no 1° nível — pode seguir rastros mesmo em terrenos difíceis. Empatia Selvagem (1°): igual à do druida. Passo Silencioso e Percurso pela Selva (7° nível): não deixa rastros e move-se normal em terreno difícil natural. Conjuração Divina (4° nível+): magias divinas limitadas da lista de patrulheiro — máximo 4° círculo. Alinhamento: qualquer. Atributos primários: Sabedoria (magias) e Destreza (arco) ou Força (duas armas). Dado de Vida d8, BBA Boa, Fortitude e Reflexos Boas, Vontade Ruim, 6 pontos de perícia por nível. Proficiências: todas as armas simples e marciais, armaduras leves e médias, todos os escudos (exceto torre). Estilo de jogo: guerreiro secundário especializado em explorar, rastrear e caçar. Excelente scout, útil em campanhas ao ar livre, complementar aos combatentes pesados. Menos poder puro que guerreiro ou bárbaro em combates simétricos, mas incomparável quando o alvo é um inimigo favorito.',
                'dado_vida'              => 8,
                'bba_progressao'         => 'boa',
                'resistencia_fortitude'  => 'boa',
                'resistencia_reflexos'   => 'boa',
                'resistencia_vontade'    => 'ruim',
                'pontos_pericia'         => 6,
            ],
        ];

        foreach ($classes as $classe) {
            Classe::updateOrCreate(
                ['nome' => $classe['nome'], 'versao' => $classe['versao']],
                $classe
            );
        }
    }
}
