<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Magia;
use App\Models\Classe;

class MagiaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('classe_magia')->truncate();
        DB::table('magias')->truncate();

        $classesMap = Classe::pluck('id', 'nome')->toArray();

        $magias = [
            // ── NÍVEL 0 ───────────────────────────────────────────────────────
            [
                'nome' => 'Resistência', 'escola' => 'Abjuração',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 minuto', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo recebe bônus de +1 em testes de resistência.',
                'classes' => ['Bardo' => 0, 'Clérigo' => 0, 'Druida' => 0, 'Paladino' => 1, 'Patrulheiro' => 1],
            ],
            [
                'nome' => 'Detectar Magia', 'escola' => 'Adivinhação',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '18 m', 'alvo_area_efeito' => 'Cone de 18 m',
                'duracao' => 'Concentração, até 1 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Detecta magias e itens mágicos em um cone de 18 m.',
                'classes' => ['Bardo' => 0, 'Clérigo' => 0, 'Druida' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Detectar Veneno', 'escola' => 'Adivinhação',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Uma criatura, um objeto ou uma área de 1,5 m×1,5 m',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Detecta veneno em uma criatura ou objeto.',
                'classes' => ['Clérigo' => 0, 'Druida' => 0, 'Paladino' => 1, 'Patrulheiro' => 1, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Leitura de Magia', 'escola' => 'Adivinhação',
                'componentes' => 'V, S, F', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Você',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Permite ler escritas mágicas e pergaminhos.',
                'classes' => ['Bardo' => 0, 'Clérigo' => 0, 'Druida' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Luz', 'escola' => 'Evocação',
                'componentes' => 'V, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Objeto tocado',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'O objeto emite luz brilhante em um raio de 6 m e penumbra por mais 6 m.',
                'classes' => ['Bardo' => 0, 'Clérigo' => 0, 'Druida' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Choque Elétrico', 'escola' => 'Evocação [Eletricidade]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um toque elétrico causa 1d3 de dano elétrico.',
                'classes' => ['Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Ácido Respingado', 'escola' => 'Conjuração (Criação) [Ácido]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Uma criatura ou objeto',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Um raio de ácido causa 1d3 de dano de ácido.',
                'classes' => ['Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Raio de Frio', 'escola' => 'Conjuração (Criação) [Frio]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Uma criatura ou objeto',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Um raio de frio causa 1d3 de dano de frio.',
                'classes' => ['Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Mão do Mago', 'escola' => 'Transmutação',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um objeto de até 2,5 kg',
                'duracao' => 'Concentração', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Move um objeto de até 2,5 kg a distância à vontade.',
                'classes' => ['Bardo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Mensagem', 'escola' => 'Transmutação [Linguagem]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um alvo/nível',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Permite sussurros mágicos para alvos designados.',
                'classes' => ['Bardo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Prestidigitação', 'escola' => 'Universal',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Consulte o texto',
                'duracao' => '1 hora', 'teste_resistencia' => 'Consulte o texto',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Executa truques menores de magia para entretenimento e distração.',
                'classes' => ['Bardo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Ruído', 'escola' => 'Ilusão (Fantasma) [Dependente de Som]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Elaborado; consulte o texto',
                'duracao' => 'Concentração (até 1 rodada/nível)', 'teste_resistencia' => 'Vontade descrença (se interagir)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria ilusão sonora de qualquer som.',
                'classes' => ['Bardo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Ilusão Menor', 'escola' => 'Ilusão (Fantasma)',
                'componentes' => 'S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Imagem de até 1,5 m³',
                'duracao' => 'Concentração', 'teste_resistencia' => 'Vontade descrença (se interagir)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria uma imagem ilusória inanimada.',
                'classes' => ['Bardo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            [
                'nome' => 'Orientação', 'escola' => 'Adivinhação',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 minuto', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo recebe bônus de +1 em sua próxima jogada de ataque, teste de resistência ou verificação de habilidade.',
                'classes' => ['Clérigo' => 0, 'Druida' => 0],
            ],
            [
                'nome' => 'Curar Ferimentos Menores', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 1 ponto de dano à criatura tocada.',
                'classes' => ['Clérigo' => 0, 'Druida' => 0],
            ],
            [
                'nome' => 'Destruir Mortos-Vivos', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um morto-vivo',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Causa 1d6 de dano a um morto-vivo.',
                'classes' => ['Clérigo' => 0, 'Mago' => 0, 'Feiticeiro' => 0],
            ],
            // ── NÍVEL 1 ───────────────────────────────────────────────────────
            [
                'nome' => 'Sono', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 rodada',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Uma ou mais criaturas em área de 3 m de raio',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Causa torpor mágico em 4 DV de criaturas.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Míssil Mágico', 'escola' => 'Evocação [Força]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Até cinco criaturas, sem duas a mais de 4,5 m de distância',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um dardo de energia mágica causa 1d4+1 de dano por míssil (1 míssil a cada 2 níveis além do 1°, máx. 5).',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Armadura Arcana', 'escola' => 'Conjuração (Criação) [Força]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 hora/nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria uma armadura invisível de força que concede +4 de bônus de armadura à CA.',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Escudo', 'escola' => 'Abjuração [Força]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Você',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Um escudo invisível de força concede +4 de bônus de escudo à CA e bloqueia mísseis mágicos.',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Encantar Pessoa', 'escola' => 'Encantamento (Encanto) [Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um humanoide',
                'duracao' => '1 hora/nível', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Faz com que um humanoide trate o conjurador como amigo leal.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Mãos Flamejantes', 'escola' => 'Evocação [Fogo]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Cone de 4,5 m',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um jato de chamas causa 1d4/nível de dano de fogo (máx. 5d4).',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Toque Elétrico', 'escola' => 'Evocação [Eletricidade]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Toque causa 1d6/nível de dano elétrico (máx. 5d6).',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Raio de Enfraquecimento', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Raio causa 1d6 de penalidade de Força (+ 1/dois níveis, máx. +5).',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Causar Medo', 'escola' => 'Necromancia [Medo, Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura viva tocada com 5 ou menos DV',
                'duracao' => '1d4 rodadas', 'teste_resistencia' => 'Vontade parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Faz a criatura ficar apavorada por 1d4 rodadas.',
                'classes' => ['Bardo' => 1, 'Clérigo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Toque Gelado', 'escola' => 'Necromancia [Frio]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura ou criaturas tocadas (até uma/nível)',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Toque causa 1d6/nível de dano (máx. 10d6) e 1d4 de penalidade de Força.',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Ampliar Pessoa', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 rodada',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um humanoide',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Fortitude anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Dobra o tamanho do humanoide alvo, aumentando FOR e reduzindo DES e CA.',
                'classes' => ['Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Queda Suave', 'escola' => 'Transmutação',
                'componentes' => 'V', 'tempo_execucao' => 'Reação imediata',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Até uma criatura/nível, sem duas a mais de 6 m',
                'duracao' => 'Até que aterrisse ou 1 rodada/nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Os alvos caem lentamente, sem sofrer dano de queda.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Identificar', 'escola' => 'Adivinhação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 hora',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Um objeto mágico',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Determina todas as propriedades mágicas de um único item mágico.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Graxa', 'escola' => 'Conjuração (Criação)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um objeto ou superfície de 3 m²',
                'duracao' => '1 rodada/nível (D)', 'teste_resistencia' => 'Consulte o texto',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cobre uma superfície com graxa escorregadia, dificultando movimento.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Imagem Silenciosa', 'escola' => 'Ilusão (Fantasma)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Imagem de até 1,5 m³/nível',
                'duracao' => 'Concentração', 'teste_resistencia' => 'Vontade descrença (se interagir)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria uma imagem visual de um objeto, criatura ou força.',
                'classes' => ['Bardo' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Curar Ferimentos Leves', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 1d8 + 1/nível (máx. +5) de dano.',
                'classes' => ['Bardo' => 1, 'Clérigo' => 1, 'Druida' => 1, 'Paladino' => 1, 'Patrulheiro' => 1],
            ],
            [
                'nome' => 'Abençoar', 'escola' => 'Encantamento (Encanto) [Mental]',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '15 m', 'alvo_area_efeito' => 'Aliados na área',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Aliados ganham +1 em jogadas de ataque e testes de resistência contra medo.',
                'classes' => ['Clérigo' => 1, 'Paladino' => 1],
            ],
            [
                'nome' => 'Proteção contra o Mal', 'escola' => 'Abjuração [Bem]',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Concede +2 de deflexão à CA e +2 nos testes de resistência contra criaturas más; protege de controle mental.',
                'classes' => ['Clérigo' => 1, 'Paladino' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Infligir Ferimentos Leves', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Toque causa 1d8 + 1/nível (máx. +5) de dano.',
                'classes' => ['Clérigo' => 1],
            ],
            [
                'nome' => 'Salto', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede bônus de +30 na perícia Saltar.',
                'classes' => ['Druida' => 1, 'Patrulheiro' => 1, 'Mago' => 1, 'Feiticeiro' => 1],
            ],
            [
                'nome' => 'Entrelaçar', 'escola' => 'Transmutação',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Plantas em área de 12 m de raio',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Reflexos parcial',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Plantas agarram e prendem criaturas na área.',
                'classes' => ['Druida' => 1, 'Patrulheiro' => 1],
            ],
            // ── NÍVEL 2 ───────────────────────────────────────────────────────
            [
                'nome' => 'Invisibilidade', 'escola' => 'Ilusão (Glamer)',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal ou toque', 'alvo_area_efeito' => 'Você ou a criatura tocada',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo torna-se invisível. Termina se atacar.',
                'classes' => ['Bardo' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Imagem Especular', 'escola' => 'Ilusão (Fantasma)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Você',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria 1d4+1/3 níveis cópias ilusórias (máx. 8) do conjurador.',
                'classes' => ['Bardo' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Raio Escaldante', 'escola' => 'Evocação [Fogo]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ou mais raios',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um raio de fogo causa 4d6 de dano de fogo (até três raios acima do 11°).',
                'classes' => ['Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Teia', 'escola' => 'Conjuração (Criação)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Teias em área de 4 m de raio',
                'duracao' => '10 min./nível (D)', 'teste_resistencia' => 'Reflexos anula; consulte o texto',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria uma massa de fios pegajosos que prendem criaturas.',
                'classes' => ['Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Poeira Brilhante', 'escola' => 'Conjuração (Criação)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Criaturas e objetos em área de 3 m de raio',
                'duracao' => '1 rodada/nível', 'teste_resistencia' => 'Vontade parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cobre tudo em poeira brilhante que cega e impede invisibilidade.',
                'classes' => ['Bardo' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Ver Invisível', 'escola' => 'Adivinhação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Você',
                'duracao' => '10 min./nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Revela criaturas e objetos invisíveis.',
                'classes' => ['Bardo' => 3, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Detectar Pensamentos', 'escola' => 'Adivinhação [Mental]',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '18 m', 'alvo_area_efeito' => 'Cone de 18 m',
                'duracao' => 'Concentração, até 1 min./nível', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Permite ouvir os pensamentos superficiais de criaturas.',
                'classes' => ['Bardo' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Força do Touro', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria na Força.',
                'classes' => ['Clérigo' => 2, 'Druida' => 2, 'Paladino' => 2, 'Patrulheiro' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Graça do Gato', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria na Destreza.',
                'classes' => ['Bardo' => 2, 'Druida' => 2, 'Patrulheiro' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Resistência do Urso', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria na Constituição.',
                'classes' => ['Clérigo' => 2, 'Druida' => 2, 'Paladino' => 2, 'Patrulheiro' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Astúcia da Raposa', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria na Inteligência.',
                'classes' => ['Bardo' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Sabedoria da Coruja', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria na Sabedoria.',
                'classes' => ['Clérigo' => 2, 'Druida' => 2, 'Paladino' => 2, 'Patrulheiro' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Esplendor da Águia', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'O alvo ganha +4 de melhoria no Carisma.',
                'classes' => ['Bardo' => 2, 'Clérigo' => 2, 'Paladino' => 2, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Levitar', 'escola' => 'Transmutação',
                'componentes' => 'V, S, F', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal ou próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Você, um objeto ou uma criatura',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Permite mover-se verticalmente a até 6 m por rodada.',
                'classes' => ['Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Cegueira/Surdez', 'escola' => 'Necromancia',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => 'Permanente (D)', 'teste_resistencia' => 'Fortitude anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Torna um ser cego ou surdo permanentemente.',
                'classes' => ['Bardo' => 2, 'Clérigo' => 3, 'Mago' => 2, 'Feiticeiro' => 2],
            ],
            [
                'nome' => 'Silêncio', 'escola' => 'Ilusão (Glamer)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Área de 4,5 m de raio',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula; consulte o texto',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Nenhum som pode ser criado ou passar pela área.',
                'classes' => ['Bardo' => 2, 'Clérigo' => 2],
            ],
            [
                'nome' => 'Curar Ferimentos Moderados', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 2d8 + 1/nível (máx. +10) de dano.',
                'classes' => ['Bardo' => 3, 'Clérigo' => 2, 'Druida' => 3, 'Paladino' => 3],
            ],
            [
                'nome' => 'Imobilizar Pessoa', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um humanoide',
                'duracao' => '1 rodada/nível (D)', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Paralisa um humanoide.',
                'classes' => ['Bardo' => 2, 'Clérigo' => 2, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            // ── NÍVEL 3 ───────────────────────────────────────────────────────
            [
                'nome' => 'Bola de Fogo', 'escola' => 'Evocação [Fogo]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Explosão com 6 m de raio',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Uma explosão de chama causa 1d6/nível (máx. 10d6) de dano de fogo.',
                'classes' => ['Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Relâmpago', 'escola' => 'Evocação [Eletricidade]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '30 m', 'alvo_area_efeito' => 'Relâmpago de 30 m',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um raio de eletricidade causa 1d6/nível (máx. 10d6) de dano elétrico.',
                'classes' => ['Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Voar', 'escola' => 'Transmutação',
                'componentes' => 'V, S, F', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede deslocamento de voo de 18 m (boa manobrabilidade).',
                'classes' => ['Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Rapidez', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Uma criatura/nível, sem duas a mais de 9 m',
                'duracao' => '1 rodada/nível', 'teste_resistencia' => 'Fortitude anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um alvo por nível move-se e age com o dobro da velocidade; +1 em ataques, CA e Reflexos.',
                'classes' => ['Bardo' => 6, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Dissipar Magia', 'escola' => 'Abjuração',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Uma magia, conjurador ou criatura',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cancela magias e efeitos mágicos.',
                'classes' => ['Bardo' => 3, 'Clérigo' => 3, 'Druida' => 4, 'Paladino' => 3, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Toque Vampírico', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Ser vivo tocado',
                'duracao' => 'Instantânea/1 hora; consulte o texto', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Toque causa 1d6/dois níveis de dano (máx. 10d6); você ganha os PVs perdidos como temporários.',
                'classes' => ['Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Heroísmo', 'escola' => 'Encantamento (Encanto) [Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede +2 em jogadas de ataque, testes de resistência e verificações de habilidade.',
                'classes' => ['Bardo' => 2, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Sono Profundo', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 rodada',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Uma ou mais criaturas em área de 3 m de raio',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Causa torpor mágico em 10 DV de criaturas.',
                'classes' => ['Bardo' => 3, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Proteção contra Energia', 'escola' => 'Abjuração',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '10 min./nível ou até ser descarregado', 'teste_resistencia' => 'Fortitude anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Absorve até 12 pontos/nível de dano de um tipo de energia (máx. 120).',
                'classes' => ['Clérigo' => 3, 'Druida' => 3, 'Patrulheiro' => 2, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            [
                'nome' => 'Curar Ferimentos Sérios', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 3d8 + 1/nível (máx. +15) de dano.',
                'classes' => ['Clérigo' => 3, 'Druida' => 4],
            ],
            [
                'nome' => 'Oração', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S, FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '12 m', 'alvo_area_efeito' => 'Todos os aliados e inimigos em 12 m de raio',
                'duracao' => '1 rodada/nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Aliados ganham +1 em ataques, dano, testes de resistência e perícias; inimigos sofrem penalidade de -1.',
                'classes' => ['Clérigo' => 3, 'Paladino' => 3],
            ],
            [
                'nome' => 'Línguas', 'escola' => 'Adivinhação',
                'componentes' => 'V, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Permite compreender e falar qualquer idioma.',
                'classes' => ['Bardo' => 2, 'Clérigo' => 4, 'Mago' => 3, 'Feiticeiro' => 3],
            ],
            // ── NÍVEL 4 ───────────────────────────────────────────────────────
            [
                'nome' => 'Porta Dimensional', 'escola' => 'Conjuração (Teletransporte)',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Você e objetos tocados',
                'duracao' => 'Instantânea e até 1 rodada; consulte o texto', 'teste_resistencia' => 'Nenhum e Vontade anula',
                'resistencia_magia' => 'Não e Sim', 'versao' => '3.5',
                'descricao' => 'Teletransporta você e, possivelmente, outros para um local designado.',
                'classes' => ['Bardo' => 4, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Invisibilidade Superior', 'escola' => 'Ilusão (Glamer)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal ou toque', 'alvo_area_efeito' => 'Você ou criatura tocada',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Semelhante a Invisibilidade, mas o alvo permanece invisível mesmo ao atacar.',
                'classes' => ['Bardo' => 4, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Tempestade de Gelo', 'escola' => 'Evocação [Frio]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Cilindro de 6 m de raio e 12 m de altura',
                'duracao' => '1 rodada completa', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Granizo causa 3d6 de dano contuso e 2d6 de dano de frio a tudo na área.',
                'classes' => ['Druida' => 4, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Pele de Pedra', 'escola' => 'Abjuração',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede RD 10/adamanto.',
                'classes' => ['Druida' => 6, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Enervação', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Raio causa 1d4 níveis negativos ao alvo.',
                'classes' => ['Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Assassino Fantasmagórico', 'escola' => 'Ilusão (Fantasma) [Medo, Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade descrença e Fortitude metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Uma imagem aterrorizante da morte do alvo causa dano potencialmente letal.',
                'classes' => ['Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Medo', 'escola' => 'Necromancia [Medo, Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '9 m', 'alvo_area_efeito' => 'Cone de 9 m',
                'duracao' => '1 rodada/nível', 'teste_resistencia' => 'Vontade parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Criaturas na área ficam apavoradas.',
                'classes' => ['Bardo' => 3, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Animar Mortos', 'escola' => 'Necromancia [Mal]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Um ou mais esqueletos ou zumbis',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria mortos-vivos não-inteligentes a partir de cadáveres e ossos.',
                'classes' => ['Clérigo' => 3, 'Mago' => 4, 'Feiticeiro' => 4],
            ],
            [
                'nome' => 'Curar Ferimentos Críticos', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 4d8 + 1/nível (máx. +20) de dano.',
                'classes' => ['Clérigo' => 4, 'Druida' => 5],
            ],
            [
                'nome' => 'Neutralizar Veneno', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S, M/FD', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura, objeto ou área de 1,5 m³',
                'duracao' => '10 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva, objeto)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Detoxifica qualquer veneno no alvo.',
                'classes' => ['Bardo' => 4, 'Clérigo' => 4, 'Druida' => 3, 'Paladino' => 4, 'Patrulheiro' => 3],
            ],
            // ── NÍVEL 5 ───────────────────────────────────────────────────────
            [
                'nome' => 'Cone de Frio', 'escola' => 'Evocação [Frio]',
                'componentes' => 'V, S, M/F', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '15 m', 'alvo_area_efeito' => 'Cone de 15 m',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Jato de frio causa 1d6/nível (máx. 15d6) de dano de frio.',
                'classes' => ['Mago' => 5, 'Feiticeiro' => 5],
            ],
            [
                'nome' => 'Dominar Pessoa', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 rodada',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um humanoide',
                'duracao' => '1 dia/nível', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Controla o humanoide alvo telepáticamente.',
                'classes' => ['Bardo' => 4, 'Mago' => 5, 'Feiticeiro' => 5],
            ],
            [
                'nome' => 'Telecinesia', 'escola' => 'Transmutação',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Consulte o texto',
                'duracao' => 'Concentração, até 1 rodada/nível, ou instantânea; consulte o texto', 'teste_resistencia' => 'Vontade anula (objeto)',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Move objetos ou criaturas usando somente a força da mente.',
                'classes' => ['Mago' => 5, 'Feiticeiro' => 5],
            ],
            [
                'nome' => 'Imobilizar Monstro', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => '1 rodada/nível (D)', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Paralisa qualquer criatura, não apenas humanoide.',
                'classes' => ['Bardo' => 4, 'Clérigo' => 6, 'Mago' => 5, 'Feiticeiro' => 5],
            ],
            [
                'nome' => 'Parede de Força', 'escola' => 'Evocação [Força]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Parede de força de até 3 m²/nível',
                'duracao' => '1 min./nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Uma parede invisível e invulnerável de força.',
                'classes' => ['Mago' => 5, 'Feiticeiro' => 5],
            ],
            [
                'nome' => 'Curar Ferimentos em Massa (Leves)', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Várias criaturas, sem duas a mais de 9 m',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade metade (inofensiva) ou Vontade metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Cura 1d8 + 1/nível (máx. +25) em múltiplos aliados.',
                'classes' => ['Clérigo' => 5, 'Druida' => 6],
            ],
            [
                'nome' => 'Ressuscitar', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 minuto',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura morta tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum; Consulte o texto',
                'resistencia_magia' => 'Sim (inofensiva)', 'versao' => '3.5',
                'descricao' => 'Retorna um ser morto à vida (até 10 anos morto). Perde um nível permanentemente.',
                'classes' => ['Clérigo' => 5],
            ],
            [
                'nome' => 'Visão Verdadeira', 'escola' => 'Adivinhação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede visão da verdade, revelando ilusões, formas ocultas, plano etéreo e invisíveis.',
                'classes' => ['Clérigo' => 5, 'Druida' => 7, 'Mago' => 6, 'Feiticeiro' => 6],
            ],
            // ── NÍVEL 6 ───────────────────────────────────────────────────────
            [
                'nome' => 'Relâmpago em Corrente', 'escola' => 'Evocação [Eletricidade]',
                'componentes' => 'V, S, F', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Um alvo primário mais um/nível (até 20)',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um relâmpago salta entre alvos causando 1d6/nível (máx. 20d6); alvos secundários: 1d6/dois níveis.',
                'classes' => ['Mago' => 6, 'Feiticeiro' => 6],
            ],
            [
                'nome' => 'Desintegrar', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um ser vivo ou objeto',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Um raio causa 2d6/nível (máx. 40d6) de dano; se matar, o alvo vira pó.',
                'classes' => ['Mago' => 6, 'Feiticeiro' => 6],
            ],
            [
                'nome' => 'Globo de Invulnerabilidade', 'escola' => 'Abjuração',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '3 m', 'alvo_area_efeito' => 'Esfera de 3 m de raio centrada em você',
                'duracao' => '1 rodada/nível (D)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria uma barreira imóvel impedindo magias de 4° nível ou menos.',
                'classes' => ['Mago' => 6, 'Feiticeiro' => 6],
            ],
            [
                'nome' => 'Criar Mortos-Vivos', 'escola' => 'Necromancia [Mal]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 hora',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Um ou mais cadáveres',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Cria mortos-vivos mais poderosos: ghoul, ghast, mummy, mohrg, etc.',
                'classes' => ['Clérigo' => 6, 'Mago' => 6, 'Feiticeiro' => 6],
            ],
            [
                'nome' => 'Heroísmo Superior', 'escola' => 'Encantamento (Encanto) [Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 min./nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Concede +4 em ataques, testes de resistência e verificações; mais 2d10 PVs temporários e imunidade a medo.',
                'classes' => ['Bardo' => 5, 'Mago' => 6, 'Feiticeiro' => 6],
            ],
            // ── NÍVEL 7 ───────────────────────────────────────────────────────
            [
                'nome' => 'Bola de Fogo de Explosão Retardada', 'escola' => 'Evocação [Fogo]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Explosão com 6 m de raio',
                'duracao' => '5 rodadas ou menos; consulte o texto', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Bola de fogo de detonação retardada causando 1d6/nível (máx. 20d6).',
                'classes' => ['Mago' => 7, 'Feiticeiro' => 7],
            ],
            [
                'nome' => 'Dedo da Morte', 'escola' => 'Necromancia [Morte]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude parcial',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Mata instantaneamente; se salvar, sofre 3d6 + 1/nível de dano.',
                'classes' => ['Druida' => 8, 'Mago' => 7, 'Feiticeiro' => 7],
            ],
            [
                'nome' => 'Reverter Gravidade', 'escola' => 'Transmutação',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Área cilíndrica de 6 m de raio e 18 m de altura',
                'duracao' => '1 rodada/nível (D)', 'teste_resistencia' => 'Reflexos anula; consulte o texto',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Inverte a gravidade em uma área, fazendo criaturas e objetos caírem para o teto.',
                'classes' => ['Mago' => 7, 'Feiticeiro' => 7],
            ],
            [
                'nome' => 'Insanidade', 'escola' => 'Encantamento (Compulsão) [Mental]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Um ser vivo',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Vontade anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Torna o alvo permanentemente insano (como confusão permanente).',
                'classes' => ['Mago' => 7, 'Feiticeiro' => 7],
            ],
            [
                'nome' => 'Ressurreição', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S, M', 'tempo_execucao' => '10 minutos',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura morta tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum; consulte o texto',
                'resistencia_magia' => 'Sim (inofensiva)', 'versao' => '3.5',
                'descricao' => 'Retorna um morto à vida mesmo sem corpo completo. Recupera nível perdido por Ressuscitar.',
                'classes' => ['Clérigo' => 7],
            ],
            // ── NÍVEL 8 ───────────────────────────────────────────────────────
            [
                'nome' => 'Murcha Horrível', 'escola' => 'Necromancia',
                'componentes' => 'V, S, M', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Até um ser/nível em área de 18 m de raio',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Drena toda a umidade das criaturas causando 1d6/nível (máx. 20d6) de dano.',
                'classes' => ['Mago' => 8, 'Feiticeiro' => 8],
            ],
            [
                'nome' => 'Nuvem Incendiária', 'escola' => 'Conjuração (Criação) [Fogo]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Nuvem em área de 6 m de raio',
                'duracao' => '1 rodada/nível', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Uma nuvem de brasas causa 4d6 de dano de fogo por rodada.',
                'classes' => ['Mago' => 8, 'Feiticeiro' => 8],
            ],
            [
                'nome' => 'Palavra de Poder: Atordoar', 'escola' => 'Encantamento (Compulsão) [Mental, Linguagem]',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ser vivo com 150 PVs ou menos',
                'duracao' => 'Consulte o texto', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Atordoa uma criatura por duração baseada nos PVs atuais dela.',
                'classes' => ['Mago' => 8, 'Feiticeiro' => 8],
            ],
            [
                'nome' => 'Símbolo da Morte', 'escola' => 'Necromancia [Morte]',
                'componentes' => 'V, S, M', 'tempo_execucao' => '10 minutos',
                'alcance' => '0 m; consulte o texto', 'alvo_area_efeito' => 'Área de 18 m de raio',
                'duracao' => 'Consulte o texto', 'teste_resistencia' => 'Fortitude anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Símbolo gravado mata criaturas com 150 PVs ou menos que o vejam.',
                'classes' => ['Clérigo' => 8, 'Mago' => 8, 'Feiticeiro' => 8],
            ],
            [
                'nome' => 'Mente em Branco', 'escola' => 'Abjuração',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura tocada',
                'duracao' => '1 dia/nível', 'teste_resistencia' => 'Vontade anula (inofensiva)',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Imunidade a magias de adivinhação e afins; protege totalmente a mente.',
                'classes' => ['Mago' => 8, 'Feiticeiro' => 8],
            ],
            // ── NÍVEL 9 ───────────────────────────────────────────────────────
            [
                'nome' => 'Desejo', 'escola' => 'Universal',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Consulte o texto', 'alvo_area_efeito' => 'Consulte o texto',
                'duracao' => 'Consulte o texto', 'teste_resistencia' => 'Consulte o texto',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'A mais poderosa magia arcana; pode duplicar qualquer magia de 8° nível ou menos e realizar prodígios.',
                'classes' => ['Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Enxame de Meteoros', 'escola' => 'Evocação [Fogo]',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Longo (120 m + 12 m/nível)', 'alvo_area_efeito' => 'Quatro explosões de 12 m de raio cada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Reflexos metade',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Quatro meteoros causam 2d6 de dano contuso e 6d6 de fogo cada.',
                'classes' => ['Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Parar o Tempo', 'escola' => 'Transmutação',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Pessoal', 'alvo_area_efeito' => 'Você',
                'duracao' => '1d4+1 rodadas (percebido pelo conjurador)', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Para o fluxo do tempo para todos além de você. Você age normalmente por 1d4+1 rounds.',
                'classes' => ['Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Palavra de Poder: Matar', 'escola' => 'Encantamento (Compulsão) [Mental, Linguagem, Morte]',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Próximo (7,5 m + 1,5 m/2 níveis)', 'alvo_area_efeito' => 'Um ser vivo com 100 PVs ou menos',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Mata instantaneamente um ser vivo com 100 PVs ou menos.',
                'classes' => ['Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Lamento da Banshee', 'escola' => 'Necromancia [Morte, Sonic]',
                'componentes' => 'V', 'tempo_execucao' => '1 ação padrão',
                'alcance' => '0 m; consulte o texto', 'alvo_area_efeito' => 'Um ser vivo/nível em área de 15 m de raio',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude anula',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Grito sobrenatural mata todos os seres vivos na área de efeito.',
                'classes' => ['Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Portal', 'escola' => 'Conjuração (Criação e Teletransporte)',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Médio (30 m + 3 m/nível)', 'alvo_area_efeito' => 'Consulte o texto',
                'duracao' => 'Concentração + 2 rodadas/nível', 'teste_resistencia' => 'Nenhum',
                'resistencia_magia' => 'Não', 'versao' => '3.5',
                'descricao' => 'Abre um portal para outro plano de existência. Pode convocar seres de outros planos.',
                'classes' => ['Clérigo' => 9, 'Mago' => 9, 'Feiticeiro' => 9],
            ],
            [
                'nome' => 'Ressurreição Total', 'escola' => 'Conjuração (Cura)',
                'componentes' => 'V, S, M, FD', 'tempo_execucao' => '10 minutos',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Criatura morta tocada',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Nenhum; consulte o texto',
                'resistencia_magia' => 'Sim (inofensiva)', 'versao' => '3.5',
                'descricao' => 'Retorna qualquer morto à vida sem perda de nível, mesmo após séculos.',
                'classes' => ['Clérigo' => 9],
            ],
            [
                'nome' => 'Drenar Energia', 'escola' => 'Necromancia',
                'componentes' => 'V, S', 'tempo_execucao' => '1 ação padrão',
                'alcance' => 'Toque', 'alvo_area_efeito' => 'Ser vivo tocado',
                'duracao' => 'Instantânea', 'teste_resistencia' => 'Fortitude parcial; consulte o texto',
                'resistencia_magia' => 'Sim', 'versao' => '3.5',
                'descricao' => 'Toque causa 2d4 níveis negativos permanentes.',
                'classes' => ['Clérigo' => 9, 'Mago' => 9, 'Feiticeiro' => 9],
            ],
        ];

        foreach ($magias as $data) {
            $classesData = $data['classes'];
            unset($data['classes']);

            $magia = Magia::updateOrCreate(
                ['nome' => $data['nome'], 'versao' => $data['versao']],
                $data
            );

            $sync = [];
            foreach ($classesData as $nomeClasse => $nivel) {
                if (isset($classesMap[$nomeClasse])) {
                    $sync[$classesMap[$nomeClasse]] = ['nivel' => $nivel];
                }
            }
            $magia->classes()->sync($sync);
        }
    }
}
