<?php

namespace Database\Seeders;

use App\Models\Raca;
use Illuminate\Database\Seeder;

class RacaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $racas = [
            // --- D&D 5.0 ---
            [
                'nome' => 'Anão (5.0)',
                'versao' => '5.0',
                'descricao' => 'Resistentes e corajosos, os anões são conhecidos por sua habilidade em combate, resistência a danos e conhecimento de mineração e trabalhos em pedra.',
                'mod_forca' => 0,
                'mod_destreza' => 0,
                'mod_constituicao' => 2,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Médio',
                'deslocamento' => 7,
            ],
            [
                'nome' => 'Elfo (5.0)',
                'versao' => '5.0',
                'descricao' => 'Elfos são um povo mágico de graça sobrenatural, vivendo no mundo sem serem inteiramente parte dele.',
                'mod_forca' => 0,
                'mod_destreza' => 2,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Halfling (5.0)',
                'versao' => '5.0',
                'descricao' => 'As pequenas pessoas dos mundos de D&D, conhecidas por sua sorte, agilidade e natureza furtiva.',
                'mod_forca' => 0,
                'mod_destreza' => 2,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Pequeno',
                'deslocamento' => 7,
            ],
            [
                'nome' => 'Humano (5.0)',
                'versao' => '5.0',
                'descricao' => 'Humanos são os mais adaptáveis e ambiciosos entre as raças comuns. Eles têm instituições e culturas amplamente variadas.',
                'mod_forca' => 1,
                'mod_destreza' => 1,
                'mod_constituicao' => 1,
                'mod_inteligencia' => 1,
                'mod_sabedoria' => 1,
                'mod_carisma' => 1,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Draconato (5.0)',
                'versao' => '5.0',
                'descricao' => 'Descendentes de dragões, os draconatos possuem um sopro elemental e uma aparência imponente.',
                'mod_forca' => 2,
                'mod_destreza' => 0,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 1,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Gnomo (5.0)',
                'versao' => '5.0',
                'descricao' => 'Gnomos são mestres da engenharia e da ilusão, com mentes brilhantes e um entusiasmo contagiante pela vida.',
                'mod_forca' => 0,
                'mod_destreza' => 0,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 2,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Pequeno',
                'deslocamento' => 7,
            ],
            [
                'nome' => 'Meio-Elfo (5.0)',
                'versao' => '5.0',
                'descricao' => 'Caminhando em dois mundos mas não pertencendo a nenhum, os meio-elfos combinam as melhores qualidades de humanos e elfos.',
                'mod_forca' => 0,
                'mod_destreza' => 1,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 1,
                'mod_sabedoria' => 0,
                'mod_carisma' => 2,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Meio-Orc (5.0)',
                'versao' => '5.0',
                'descricao' => 'Fortes e ferozes, os meio-orcs possuem uma vitalidade incrível e uma força física intimidadora.',
                'mod_forca' => 2,
                'mod_destreza' => 0,
                'mod_constituicao' => 1,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Tiefling (5.0)',
                'versao' => '5.0',
                'descricao' => 'Marcados por uma linhagem infernal, os tieflings são frequentemente vistos com desconfiança, mas possuem intelecto e carisma naturais.',
                'mod_forca' => 0,
                'mod_destreza' => 0,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 1,
                'mod_sabedoria' => 0,
                'mod_carisma' => 2,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],

            // --- D&D 3.5 ---
            [
                'nome' => 'Anão (3.5)',
                'versao' => '3.5',
                'descricao' => 'Os anões são conhecidos por sua habilidade em combate, resistência a castigos físicos e mágicos.',
                'mod_forca' => 0,
                'mod_destreza' => 0,
                'mod_constituicao' => 2,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => -2,
                'tamanho' => 'Médio',
                'deslocamento' => 6,
            ],
            [
                'nome' => 'Elfo (3.5)',
                'versao' => '3.5',
                'descricao' => 'Elfos são conhecidos por sua poesia, dança, música, magia e artes, preferindo a liberdade das florestas.',
                'mod_forca' => 0,
                'mod_destreza' => 2,
                'mod_constituicao' => -2,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Gnomo (3.5)',
                'versao' => '3.5',
                'descricao' => 'Gnomos são bem-vindos em qualquer lugar como técnicos, alquimistas e inventores.',
                'mod_forca' => -2,
                'mod_destreza' => 0,
                'mod_constituicao' => 2,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Pequeno',
                'deslocamento' => 6,
            ],
            [
                'nome' => 'Halfling (3.5)',
                'versao' => '3.5',
                'descricao' => 'Halflings são andarilhos espertos e práticos, que preferem evitar problemas mas são muito ágeis.',
                'mod_forca' => -2,
                'mod_destreza' => 2,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Pequeno',
                'deslocamento' => 6,
            ],
            [
                'nome' => 'Humano (3.5)',
                'versao' => '3.5',
                'descricao' => 'Humanos são os mais comuns dos povos, conhecidos por sua versatilidade e ambição.',
                'mod_forca' => 0,
                'mod_destreza' => 0,
                'mod_constituicao' => 0,
                'mod_inteligencia' => 0,
                'mod_sabedoria' => 0,
                'mod_carisma' => 0,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
            [
                'nome' => 'Meio-Orc (3.5)',
                'versao' => '3.5',
                'descricao' => 'Meio-orcs são conhecidos por sua força física e resistência, muitas vezes vivendo nas fronteiras da civilização.',
                'mod_forca' => 2,
                'mod_destreza' => 0,
                'mod_constituicao' => 0,
                'mod_inteligencia' => -2,
                'mod_sabedoria' => 0,
                'mod_carisma' => -2,
                'tamanho' => 'Médio',
                'deslocamento' => 9,
            ],
        ];

        foreach ($racas as $raca) {
            Raca::updateOrCreate(['nome' => $raca['nome']], $raca);
        }
    }
}
