<?php

namespace Database\Seeders;

use App\Models\Tendencia;
use Illuminate\Database\Seeder;

class TendenciaSeeder extends Seeder
{
    public function run(): void
    {
        $tendencias = [
            [
                'nome' => 'Leal e Bom',
                'apelido' => 'O Cruzado',
                'iniciais' => 'LB',
                'descricao' => "O Leal e Bom acredita que uma sociedade organizada, guiada por leis justas, é o melhor caminho para promover o bem coletivo. Age com honra, respeita autoridade legítima, protege inocentes e combate a tirania pelo lado direito das regras.\n\n**Mundivisão**: a ordem estruturada é a fundação da civilização. Leis justas devem ser seguidas mesmo quando inconvenientes, porque quebrá-las estabelece precedentes perigosos. O bem é servir os outros dentro de um sistema ético.\n**Comportamento Típico**: cumpre promessas mesmo com custo pessoal; respeita hierarquias legítimas; combate o mal ativamente mas apenas por meios legais; ajuda estranhos em necessidade; abomina traições e mentiras.\n**Exemplos Literários**: Superman, o Rei Arthur, Aragorn (Rei de Gondor), a maioria dos paladinos clássicos.\n**Classes Típicas**: **Paladino** (obrigatório), **Clérigos** de deuses bons e legais (Heironeous, Moradin, Yondalla, Pelor), **Monges** dedicados à ordem sagrada, alguns **Guerreiros** cavaleiros.\n**Restrições de Classe**: exclusivo do Paladino; Bárbaros e Bardos NÃO podem ser leais (a lealdade extrema é incompatível com a fúria e a espontaneidade artística).\n**Motivações Comuns**: proteção dos fracos, preservação da tradição, cumprimento de juramentos sagrados, cruzada contra o mal organizado.\n**Tensão Filosófica**: pode entrar em conflito com Bons Neutros e Caóticos que veem leis injustas como algo a ser desobedecido — o Leal e Bom acredita que mesmo leis imperfeitas merecem respeito enquanto não são reformadas legalmente.",
            ],
            [
                'nome' => 'Neutro e Bom',
                'apelido' => 'O Benfeitor',
                'iniciais' => 'NB',
                'descricao' => "O Neutro e Bom é guiado principalmente pela consciência e pelo desejo genuíno de fazer o bem. Não se preocupa em seguir leis por serem leis, nem em quebrá-las por rebeldia — apenas em ajudar os outros de forma efetiva, seja pelos meios convencionais ou não.\n\n**Mundivisão**: o bem é um fim em si mesmo; leis e ordens são apenas ferramentas. Se uma lei injusta impede o bem, deve ser questionada; se a lei justa serve o bem, deve ser respeitada. O importante é o resultado ético.\n**Comportamento Típico**: ajuda quando pode, sem se preocupar com quem manda o quê; respeita autoridade quando ela merece; questiona leis injustas educadamente; combate o mal por qualquer meio ético disponível; mantém amizades acima de facções.\n**Exemplos Literários**: Gandalf, Samwise Gamgee, muitos druidas e sacerdotes rurais, curadores itinerantes.\n**Classes Típicas**: **Clérigos** de deuses neutros e bons (Pelor, Ehlonna, Yondalla), **Druidas** benevolentes, **Bardos** benevolentes, **Curadores** de vila.\n**Motivações Comuns**: nutrir a vida, curar os feridos, proteger os inocentes independente de nacionalidade, guiar os perdidos moralmente.\n**Tensão Filosófica**: pode chocar-se com Leais e Bons que insistem em seguir leis mesmo injustas; e com Caóticos e Bons que veem qualquer lei como opressiva.",
            ],
            [
                'nome' => 'Caótico e Bom',
                'apelido' => 'O Rebelde',
                'iniciais' => 'CB',
                'descricao' => "O Caótico e Bom age conforme sua própria bússola moral, valorizando a liberdade individual acima de governos ou tradições. Faz o bem sem se importar com a maneira \"apropriada\" de fazê-lo — muitas vezes desafiando leis, hierarquias e convenções sociais para proteger os fracos.\n\n**Mundivisão**: a liberdade individual é sagrada; nenhum governo, tradição ou instituição tem direito absoluto sobre a consciência de uma pessoa. O bem exige questionar e desafiar sistemas opressivos, mesmo quando eles se autoproclamam justos.\n**Comportamento Típico**: rouba dos ricos e dá aos pobres; desobedece leis que consideram injustas; ajuda oprimidos contra opressores; desconfia de autoridades; valoriza amigos acima de instituições; abomina tirania.\n**Exemplos Literários**: Robin Hood, Han Solo (parcialmente), muitos rebeldes contra tiranos, elfos silvestres livres, ladinos com coração de ouro.\n**Classes Típicas**: **Bárbaros** benevolentes, **Bardos** rebeldes, **Ladinos** amistosos, **Clérigos** de Corellon ou Kord, **Druidas** silvestres.\n**Restrições de Classe**: Paladinos NÃO podem ser caóticos (a lealdade é essencial ao paladinato).\n**Motivações Comuns**: libertar oprimidos, punir tiranos, ajudar viajantes e refugiados, preservar liberdade individual, combater o mal organizado com métodos não-organizados.\n**Tensão Filosófica**: choca-se com Leais e Bons (que veem sua desobediência como problemática); pode ser confundido com Caóticos e Neutros (que agem por prazer, não por consciência).",
            ],
            [
                'nome' => 'Leal e Neutro',
                'apelido' => 'O Juiz',
                'iniciais' => 'LN',
                'descricao' => "O Leal e Neutro segue um código de conduta, lei ou tradição de forma rígida, sem se preocupar particularmente com o bem ou o mal. Para ele, a ordem é a virtude suprema — as consequências éticas específicas importam menos que a estabilidade do sistema.\n\n**Mundivisão**: a estrutura, disciplina e tradição são intrínsecamente boas. Um mundo sem ordem é caos, e caos é o pior dos males. Se uma lei existe, deve ser cumprida; se um código dita comportamento, deve ser seguido — a ética específica é secundária.\n**Comportamento Típico**: cumpre a letra da lei mesmo quando o espírito clama por flexibilidade; segue tradições ancestrais rigorosamente; respeita hierarquias baseado em posição, não em mérito; valoriza consistência e previsibilidade.\n**Exemplos Literários**: juízes rígidos, monges de ordens estritas, samurais tradicionais, burocratas que servem sistemas independente do reino.\n**Classes Típicas**: **Monges** (obrigatório), **Clérigos** de deuses legais (São Cuthbert, Wee Jas), alguns **Magos** especializados em Abjuração ou Adivinhação, **Guerreiros** cavaleiros de ordens estritas.\n**Restrições de Classe**: obrigatório para o Monge (a disciplina define a classe); Bárbaros e Bardos NÃO podem ser leais.\n**Motivações Comuns**: preservar tradição, aplicar códigos morais rígidos, cumprir juramentos independente do custo pessoal, manter estabilidade social.\n**Tensão Filosófica**: pode ser aliado ambíguo — trabalha bem com Leais e Bons contra caos maligno, mas pode se opor a eles se o \"bem\" exige quebrar leis; frequentemente choca-se com Caóticos de qualquer alinhamento.",
            ],
            [
                'nome' => 'Neutro',
                'apelido' => 'O Indeciso',
                'iniciais' => 'N',
                'descricao' => "O Neutro (Verdadeiramente Neutro) prefere o equilíbrio absoluto sobre extremos. Não tem inclinação forte nem para lei/ordem nem para o caos/liberdade, nem para o bem nem para o mal. Age conforme as circunstâncias, sem doutrinas fixas.\n\n**Mundivisão**: a Natureza é o modelo — nada é totalmente bom ou totalmente mau; caos e ordem coexistem em ciclos naturais. Extremos causam desequilíbrio, e desequilíbrio é a raiz de todo sofrimento. O sábio caminha no meio.\n**Comportamento Típico**: age pragmaticamente conforme situação; ajuda quando é conveniente; recusa a defender causas absolutas; observa e reflete antes de agir; questiona quem parece muito certo demais.\n**Exemplos Literários**: muitos druidas hermeticos, animais civilizados, sábios distantes, filósofos da natureza, alguns curadores neutros.\n**Classes Típicas**: **Druidas** (única classe que exige neutralidade em algum dos eixos), **Feiticeiros** neutros, **Ladinos** oportunistas éticos, **Bardos** hedonistas.\n**Restrições de Classe**: Druidas DEVEM ser neutros em pelo menos um dos eixos (Verdadeiro Neutro, Leal Neutro, Neutro Bondoso, Neutro Maligno ou Caótico Neutro).\n**Motivações Comuns**: preservar o equilíbrio da natureza, evitar extremismos, buscar sabedoria pela observação, viver conforme os ciclos naturais.\n**Tensão Filosófica**: pode ser visto como covarde ou apático por qualquer lado do eixo moral; mas os verdadeiros Neutros veem os outros alinhamentos como extremistas obsessivos.",
            ],
            [
                'nome' => 'Caótico e Neutro',
                'apelido' => 'O Espírito Livre',
                'iniciais' => 'CN',
                'descricao' => "O Caótico e Neutro segue seus impulsos e valoriza sua liberdade pessoal acima de tudo. É imprevisível — pode ajudar um estranho num dia e ignorar o mesmo estranho no seguinte, dependendo do humor. Raramente maldoso, mas nunca confiável em compromissos.\n\n**Mundivisão**: a única verdade é a experiência imediata; o resto são construções sociais opressivas. Fazer o que se quer, quando se quer, é o direito fundamental. Julgamentos morais rígidos são para os assustados.\n**Comportamento Típico**: age por impulso do momento; evita compromissos duradouros; abandona planos ao surgir algo mais interessante; valoriza aventura e novidade; abomina rotina e obrigação.\n**Exemplos Literários**: bardos boêmios errantes, exploradores excêntricos, artistas selvagens, marinheiros sem porto fixo.\n**Classes Típicas**: **Bardos** hedonistas, **Feiticeiros** imprevisíveis, **Ladinos** aventureiros, **Bárbaros** livres, muitos aventureiros errantes.\n**Restrições de Classe**: Paladinos e Monges NÃO podem ser caóticos.\n**Motivações Comuns**: liberdade absoluta, novas experiências, satisfação imediata, escapar de obrigações, viajar sem destino, buscar prazer honesto.\n**Tensão Filosófica**: pode ser mal interpretado como Caótico e Mau (ambos desprezam leis); mas Caótico Neutro NÃO deseja fazer mal, apenas seguir seus impulsos. Choca-se com Leais de qualquer eixo, que veem sua imprevisibilidade como caos social.",
            ],
            [
                'nome' => 'Leal e Mau',
                'apelido' => 'O Tirano',
                'iniciais' => 'LM',
                'descricao' => "O Leal e Mau utiliza sistemas, leis e hierarquias para obter poder, dominar outros e satisfazer seus próprios desejos malignos — sem qualquer remorso pelos que sofrem no processo. É o pior tipo de vilão: metódico, disciplinado, patriente e implacável.\n\n**Mundivisão**: os fortes existem para dominar os fracos; a ordem hierárquica é natural e desejável desde que o dominante seja ele mesmo. Leis e códigos são ferramentas de opressão; tradições devem ser respeitadas apenas quando servem ao poder.\n**Comportamento Típico**: usa a lei para prender inocentes; manipula sistemas para benefício próprio; mantém aliados fiéis por meio de terror ou lealdade forçada; nunca quebra sua palavra formal (isso destruiria sua credibilidade), mas escolhe palavras que permitam brechas; expande seu domínio metodicamente.\n**Exemplos Literários**: Sauron, tiranos históricos como César corrompido, dictadores organizados, líderes de cultos hierárquicos, príncipes malignos.\n**Classes Típicas**: **Clérigos** de deuses malignos e legais (Hextor), **Magos** especializados em Encantamento ou Necromancia com foco em dominação, **Guerreiros** cavaleiros negros, **Feiticeiros** aristocráticos.\n**Motivações Comuns**: expandir domínio, subjugar outros, acumular poder legítimo, corromper instituições, planejar longo prazo, punir traidores brutalmente.\n**Tensão Filosófica**: choca-se profundamente com Leais e Bons (mesma ênfase em ordem, propósitos opostos); pode aliar-se temporariamente com outros malignos, mas jamais confia em Caóticos.",
            ],
            [
                'nome' => 'Neutro e Mau',
                'apelido' => 'O Malfeitor',
                'iniciais' => 'NM',
                'descricao' => "O Neutro e Mau faz qualquer coisa para se beneficiar, sem consideração por leis, tradições ou outras pessoas. Não é impulsivo como o Caótico, nem metódico como o Leal — apenas puramente egoísta, calculista quando útil, oportunista quando conveniente.\n\n**Mundivisão**: o mundo existe para servi-lo; outras pessoas são recursos, obstáculos ou distrações. Não há princípios além do interesse próprio. Bem, mal, lei, caos — todos são conceitos para os fracos que se agarram a ideais.\n**Comportamento Típico**: mente, rouba e mata quando compensa; ajuda apenas quando ganha; abandona aliados na hora do risco; explora fraquezas de outros; expande poder pessoal sem cerimônia; nenhum código pessoal impede ações.\n**Exemplos Literários**: mercenários amorais, assassinos frios, aristocratas manipuladores, mestres de crime organizado, alquimistas escrupulosos.\n**Classes Típicas**: **Clérigos** de deuses neutros e malignos (Nerull, Vecna), **Magos** dedicados a poder pessoal, **Ladinos** frios sem consciência, **Feiticeiros** amorais.\n**Motivações Comuns**: poder pessoal, riqueza acumulada, controle sobre outros, sobrevivência a qualquer custo, obtenção do próprio prazer.\n**Tensão Filosófica**: pode aliar-se com qualquer alinhamento se for lucrativo; é o alinhamento mais puramente egoísta do panteão; não confia em ninguém profundamente.",
            ],
            [
                'nome' => 'Caótico e Mau',
                'apelido' => 'O Destruidor',
                'iniciais' => 'CM',
                'descricao' => "O Caótico e Mau é motivado por ganância, ódio e luxúria destruidora. Não tem respeito por leis, ordem, vida ou consequências. É o mais visceral e imediato dos alinhamentos malignos — atropela tudo que atrapalha seus caprichos, cria caos por diversão, tortura porque pode.\n\n**Mundivisão**: força e prazer imediato são as únicas realidades; tudo mais é ilusão de fracos. Regras existem para serem quebradas, ordens para serem ignoradas, promessas para serem traídas. Se sente prazer em uma ação, deve ser feita.\n**Comportamento Típico**: mata por diversão ou impulso; destrói obras alheias; trai aliados na primeira oportunidade; abandona planos ao surgir alvo mais interessante; comete atrocidades sem culpa; ri do sofrimento alheio.\n**Exemplos Literários**: berserkers sanguinários, cultistas de aniquilação, senhores de guerra imprevisíveis, brutos anárquicos.\n**Classes Típicas**: **Bárbaros** malignos, **Clérigos** de deuses caóticos e malignos (Erythnul, Tharizdun), **Bardos** cruéis, **Feiticeiros** dementes, **Ladinos** psicopatas.\n**Restrições de Classe**: Paladinos e Monges NÃO podem ser caóticos.\n**Motivações Comuns**: destruição por prazer, satisfação imediata de desejos, humilhar oponentes, provocar caos, obter poder pela força bruta.\n**Tensão Filosófica**: mesmo outros malignos evitam parceria duradoura — Caóticos e Maus são imprevisíveis demais para alianças estratégicas. Leais e Maus os consideram desperdício de potencial; Neutros e Maus os consideram amadores.",
            ],
        ];

        foreach ($tendencias as $tendencia) {
            Tendencia::updateOrCreate(
                ['iniciais' => $tendencia['iniciais']],
                $tendencia
            );
        }
    }
}
